[tool.poetry]
name = "template"
version = "0.1.0"
description = ""
authors = ["Jongsu Liam Kim <jongsukim8@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.9.2"
pylint = "^2.9.6"
isort = "^5.9.3"
black = "^21.7b0"
coverage = "^5.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
