[tool.poetry]
name = "template"
version = "0.1.0"
description = "Description"
license = "Apache License 2.0"
authors = ["Jongsu Liam Kim <jongsukim8@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8, <3.10"
click = "<8.1.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.9.2"
isort = "^5.9.3"
black = "^21.7b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ['py38', 'py39']
include = '\.pyi?$'
extend-exclude = '''
/(
  # The following are specific to Black, you probably don't want those.
  | tests/data
)/
'''

# pyproject.toml
[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "tests",
    "integration",
]
python_files = "tests/*"
log_cli = "true"
markers = [
    "slow"
]
addopts = [
    "--duration=15",
    "--strict-markers",
    "--doctest-modules"
]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::UserWarning",
]
